#!/usr/bin/env python3
# Copyright (c) 2026 Huitzo Inc. All rights reserved.
# SPDX-License-Identifier: LicenseRef-Huitzo-Proprietary

"""
Module: scripts.check_legal_headers
Description: Checks (and mechanically fixes) the Huitzo legal header on every
    first-party source file, plus repo-level license/metadata invariants.
    Stdlib only, so it runs identically in the parent repo, in every submodule
    checkout (vendored copy), in CI, and in the nightly IP-compliance sweep.

Implements:
    - docs/governance/ip-protection.md#legal-header-standard
    - docs/governance/ip-protection.md#enforcement-pipeline

See Also:
    - docs/governance/ip-protection.md#nightly-ip-compliance-sweep
    - .claude/rules/legal-headers.md

Usage:
    check_legal_headers.py                    # full-tree check (+ repo checks)
    check_legal_headers.py --diff <BASE>      # only files changed since BASE
    check_legal_headers.py --fix              # insert/complete missing headers
    check_legal_headers.py --report-json OUT  # machine-readable findings
    check_legal_headers.py --root PATH        # operate on another repo checkout

Exit codes: 0 clean, 1 findings remain, 2 usage/config error.

Runtime floor is python3.10 (no tomllib): config is JSON, and the pyproject/
Cargo metadata checks use targeted regexes instead of a TOML parser.
"""

from __future__ import annotations

import argparse
import datetime
import fnmatch
import json
import re
import subprocess
import sys
from dataclasses import asdict, dataclass
from pathlib import Path

CONFIG_NAME = ".legal-header.json"

# ext -> (comment prefix, comment suffix)
COMMENT_STYLES: dict[str, tuple[str, str]] = {
    ".py": ("# ", ""),
    ".sh": ("# ", ""),
    ".bash": ("# ", ""),
    ".rb": ("# ", ""),
    ".ts": ("// ", ""),
    ".tsx": ("// ", ""),
    ".js": ("// ", ""),
    ".jsx": ("// ", ""),
    ".mjs": ("// ", ""),
    ".cjs": ("// ", ""),
    ".rs": ("// ", ""),
    ".css": ("/* ", " */"),
    ".sql": ("-- ", ""),
}

# Directory names that are never first-party source, in any repo.
DEFAULT_EXCLUDE_DIRS = {
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    "__pycache__",
    "build",
    "coverage",
    "dist",
    "dist-node",
    "dist-standalone",
    "generated",
    "htmlcov",
    "node_modules",
    "target",
    "venv",
}

# Files whose first lines carry a generator marker are never hand-written.
GENERATED_RE = re.compile(r"auto-?generated|do not edit|generated by", re.IGNORECASE)
SPDX_RE = re.compile(r"SPDX-License-Identifier:\s*([A-Za-z0-9.+-]+)")
CODING_RE = re.compile(r"coding[:=]\s*[-\w.]+")
# How many lines from the top of a file the header must appear within.
HEAD_SCAN_LINES = 15

MECHANICAL = "mechanical"
NON_MECHANICAL = "non_mechanical"


@dataclass
class Finding:
    path: str
    kind: str  # MECHANICAL | NON_MECHANICAL
    problem: str  # missing-header | malformed-header | license-mismatch | ...
    detail: str


@dataclass
class Config:
    root: Path
    license_id: str
    holder: str
    excludes: list[str]
    metadata_files: list[str]
    repos: dict[str, str]

    @property
    def copyright_re(self) -> re.Pattern[str]:
        holder = re.escape(self.holder)
        return re.compile(rf"Copyright \(c\) \d{{4}}(?:-\d{{4}})? {holder} All rights reserved\.")


def load_config(root: Path) -> Config:
    cfg_path = root / CONFIG_NAME
    if not cfg_path.is_file():
        sys.stderr.write(f"error: {cfg_path} not found — every repo needs one (see docs)\n")
        raise SystemExit(2)
    try:
        raw = json.loads(cfg_path.read_text())
        license_id = raw["license-id"]
    except (json.JSONDecodeError, KeyError) as exc:
        sys.stderr.write(f"error: {cfg_path} invalid: {exc!r}\n")
        raise SystemExit(2) from exc
    # Config paths must stay inside the repo — reject absolute or ..-escaping
    # entries so a bad config can never read or match outside the root.
    for entry in list(raw.get("exclude", [])) + list(raw.get("metadata-files", [])):
        if entry.startswith(("/", "\\")) or ".." in entry.split("/"):
            sys.stderr.write(f"error: {cfg_path}: path escapes repo root: {entry!r}\n")
            raise SystemExit(2)
    return Config(
        root=root,
        license_id=license_id,
        holder=raw.get("copyright-holder", "Huitzo Inc."),
        excludes=list(raw.get("exclude", [])),
        metadata_files=list(raw.get("metadata-files", [])),
        repos=dict(raw.get("repos", {})),
    )


def submodule_paths(root: Path) -> set[str]:
    gitmodules = root / ".gitmodules"
    if not gitmodules.is_file():
        return set()
    return set(re.findall(r"^\s*path\s*=\s*(\S+)", gitmodules.read_text(), re.MULTILINE))


def is_excluded(relpath: str, config: Config, submodules: set[str]) -> bool:
    parts = relpath.split("/")
    if any(part in DEFAULT_EXCLUDE_DIRS for part in parts[:-1]):
        return True
    if any(relpath == sub or relpath.startswith(sub + "/") for sub in submodules):
        return True
    # fnmatch is deliberately not path-aware: `*` crosses `/`, so patterns like
    # `**/generated/**` and `apps/backend/alembic/versions/**` both just work.
    return any(fnmatch.fnmatch(relpath, pattern) for pattern in config.excludes)


def _git(root: Path, *args: str) -> str:
    result = subprocess.run(["git", *args], cwd=root, capture_output=True, text=True, check=False)
    if result.returncode != 0:
        sys.stderr.write(f"error: git {' '.join(args)} failed: {result.stderr.strip()}\n")
        raise SystemExit(2)
    return result.stdout


def discover(config: Config, diff_base: str | None) -> list[str]:
    """Candidate files as repo-relative posix paths (tracked + untracked, or diff)."""
    if diff_base:
        # Three-dot: diff against the merge-base, so files changed only on the
        # base branch (e.g. an unrebased origin/main) are never false positives.
        out = _git(config.root, "diff", "--name-only", "--diff-filter=ACMR", f"{diff_base}...HEAD")
        candidates = [line for line in out.splitlines() if line]
    else:
        out = _git(config.root, "ls-files", "-z", "--cached", "--others", "--exclude-standard")
        candidates = [tok for tok in out.split("\0") if tok]
    submodules = submodule_paths(config.root)
    selected: list[str] = []
    for rel in sorted(set(candidates)):
        if Path(rel).suffix not in COMMENT_STYLES:
            continue
        if is_excluded(rel, config, submodules):
            continue
        if not (config.root / rel).is_file():
            continue  # deleted since the diff base, or a gitlink
        selected.append(rel)
    return selected


def _read_lines(path: Path) -> list[str] | None:
    """First lines of a checkable text file; None if empty, binary, or generated."""
    try:
        text = path.read_bytes().decode("utf-8-sig")
    except UnicodeDecodeError:
        return None
    if not text.strip():
        return None
    lines = text.splitlines()
    if GENERATED_RE.search("\n".join(lines[:5])):
        return None
    return lines


def check_file(rel: str, config: Config) -> Finding | None:
    lines = _read_lines(config.root / rel)
    if lines is None:
        return None
    head = lines[:HEAD_SCAN_LINES]
    has_copyright = any(config.copyright_re.search(line) for line in head)
    spdx_ids = [m.group(1) for line in head if (m := SPDX_RE.search(line))]
    if spdx_ids and spdx_ids[0] != config.license_id:
        return Finding(
            rel,
            NON_MECHANICAL,
            "license-mismatch",
            f"header declares {spdx_ids[0]!r}, repo license is {config.license_id!r} — "
            "changing a license identifier is a legal decision, not auto-fixable",
        )
    if has_copyright and spdx_ids:
        return None
    if has_copyright or spdx_ids:
        return Finding(rel, MECHANICAL, "malformed-header", "one of the two header lines missing")
    return Finding(rel, MECHANICAL, "missing-header", "no legal header in the first lines")


def _insert_index(lines: list[str], ext: str) -> int:
    """Index at which the header block goes: after shebang and (py) coding line."""
    idx = 0
    if lines and lines[0].startswith("#!"):
        idx = 1
    if ext == ".py" and len(lines) > idx and CODING_RE.search(lines[idx]):
        idx += 1
    return idx


def fix_file(finding: Finding, config: Config) -> bool:
    """Mechanically repair a file in place. Returns True if the file changed."""
    path = config.root / finding.path
    ext = Path(finding.path).suffix
    prefix, suffix = COMMENT_STYLES[ext]
    year = datetime.date.today().year

    raw = path.read_bytes()
    bom = raw.startswith(b"\xef\xbb\xbf")
    text = raw.decode("utf-8-sig")
    lines = text.splitlines(keepends=True)
    # Match the file's own line endings so a CRLF file doesn't end up mixed.
    nl = "\r\n" if lines and lines[0].endswith("\r\n") else "\n"
    copyright_line = (
        f"{prefix}Copyright (c) {year} {config.holder} All rights reserved.{suffix}{nl}"
    )
    spdx_line = f"{prefix}SPDX-License-Identifier: {config.license_id}{suffix}{nl}"

    if finding.problem == "missing-header":
        idx = _insert_index(lines, ext)
        block = [copyright_line, spdx_line]
        if idx < len(lines) and lines[idx].strip():
            block.append(nl)
        lines[idx:idx] = block
    elif finding.problem == "malformed-header":
        for i, line in enumerate(lines[:HEAD_SCAN_LINES]):
            if config.copyright_re.search(line):
                lines[i + 1 : i + 1] = [spdx_line]  # copyright present, SPDX missing
                break
            if SPDX_RE.search(line):
                lines[i:i] = [copyright_line]  # SPDX present, copyright missing
                break
        else:
            return False
    else:
        return False  # non-mechanical problems are never auto-fixed

    data = "".join(lines).encode("utf-8")
    if bom:
        data = b"\xef\xbb\xbf" + data
    path.write_bytes(data)
    return True


# `license = "MIT"` / `license = { text = "Proprietary" }` (regex, not a TOML
# parser, to keep the python3.10 stdlib-only floor — see module docstring).
_TOML_LICENSE_RE = re.compile(r'^license\s*=\s*(?:\{\s*text\s*=\s*)?"([^"]+)"', re.MULTILINE)
_TOML_LICENSE_FILE_RE = re.compile(r'^license-file\s*=\s*"[^"]+"', re.MULTILINE)


def _metadata_license(path: Path) -> str | None:
    """The declared license of a pyproject.toml / package.json / Cargo.toml."""
    if path.name == "package.json":
        value = json.loads(path.read_text()).get("license")
        return value if isinstance(value, str) else None
    text = path.read_text()
    if path.name == "Cargo.toml" and _TOML_LICENSE_FILE_RE.search(text):
        return "SEE-LICENSE-FILE"
    match = _TOML_LICENSE_RE.search(text)
    return match.group(1) if match else None


# license-id -> acceptable declared values per metadata file kind
METADATA_EXPECT: dict[str, dict[str, set[str]]] = {
    "LicenseRef-Huitzo-Proprietary": {
        "pyproject.toml": {"Proprietary"},
        "package.json": {"UNLICENSED"},
        "Cargo.toml": {"SEE-LICENSE-FILE"},
    },
    "LicenseRef-Huitzo-Source-Available": {
        "pyproject.toml": {"Proprietary"},
        "package.json": {"SEE LICENSE IN LICENSE"},
        "Cargo.toml": {"SEE-LICENSE-FILE"},
    },
    "MIT": {
        "pyproject.toml": {"MIT"},
        "package.json": {"MIT"},
        "Cargo.toml": {"MIT", "SEE-LICENSE-FILE"},
    },
}


def repo_checks(config: Config) -> list[Finding]:
    findings: list[Finding] = []
    if not any((config.root / name).is_file() for name in ("LICENSE", "LICENSE.md")):
        findings.append(
            Finding(
                "LICENSE",
                NON_MECHANICAL,
                "missing-license",
                f"no LICENSE file at repo root (expected text for {config.license_id})",
            )
        )
    expectations = METADATA_EXPECT.get(config.license_id, {})
    for rel in config.metadata_files:
        path = config.root / rel
        if not path.is_file():
            findings.append(
                Finding(rel, NON_MECHANICAL, "missing-metadata-file", "listed in config, absent")
            )
            continue
        accepted = expectations.get(path.name)
        if not accepted:
            continue
        declared = _metadata_license(path)
        if declared not in accepted:
            findings.append(
                Finding(
                    rel,
                    NON_MECHANICAL,
                    "metadata-license-mismatch",
                    f"declares {declared!r}, expected one of {sorted(accepted)}",
                )
            )
    return findings


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=".", help="repo checkout to operate on")
    parser.add_argument("--diff", metavar="BASE", help="only check files changed since BASE")
    parser.add_argument("--fix", action="store_true", help="insert/complete headers in place")
    parser.add_argument("--report-json", metavar="PATH", help="write findings as JSON")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    config = load_config(root)
    files = discover(config, args.diff)

    findings: list[Finding] = []
    fixed = 0
    for rel in files:
        finding = check_file(rel, config)
        if finding and args.fix and finding.kind == MECHANICAL and fix_file(finding, config):
            fixed += 1
            finding = check_file(rel, config)  # verify the fix landed
        if finding:
            findings.append(finding)

    if not args.diff:
        findings.extend(repo_checks(config))

    if args.report_json:
        report = {
            MECHANICAL: [asdict(f) for f in findings if f.kind == MECHANICAL],
            NON_MECHANICAL: [asdict(f) for f in findings if f.kind == NON_MECHANICAL],
        }
        Path(args.report_json).write_text(json.dumps(report, indent=2) + "\n")

    scope = f"--diff {args.diff}" if args.diff else "full tree"
    print(f"legal-headers: {len(files)} file(s) checked ({scope}), license {config.license_id}")
    if fixed:
        print(f"legal-headers: {fixed} file(s) fixed in place")
    if findings:
        print(f"legal-headers: {len(findings)} finding(s):")
        for f in findings:
            print(f"  [{f.kind}] {f.path}: {f.problem} — {f.detail}")
        print("hint: run `python3 scripts/check_legal_headers.py --fix` for mechanical findings")
        return 1
    print("legal-headers: OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
